tfMonitoring/config/routes.rb
Rails.application.routes.draw do

  resources :transactions

  root 'transactions#index'

  post 'transaction/set_vehicle_data.json' => 'transactions#set_vehicle_data'

  get 'transaction/generateOD' => 'transactions#generateOD'

  get 'transaction/getCSV' => 'transactions#getCSV', as: 'csv_event'

end

tfMonitoring/app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

tfMonitoring/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

tfMonitoring/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :ensure_json_format, only: :set_vehicle_data

  #Accept JSON request
  protect_from_forgery with: :null_session, only: Proc.new { |c| c.request.format.json? }

  require 'rest-client'
  require 'hbase_thrift_ruby'
  require 'csv'

  $hbaseClient = ''
  $sumOfRoute = ''
  $arrayOfEndPoint = ''
  $transport = ''

  #POST /transactions/set_vehicle_data.json
  def set_vehicle_data
    @existingRecord=Transaction.where('license_no = ?', params[:license_no]).first

    if !(@existingRecord.blank?)

      # Send POST request to Flume on Hadoop Master
      route = @existingRecord.location.to_s+'-'+params[:location]
      license_no = params[:license_no]
      time = @existingRecord.time.to_s
      var = route+'|'+license_no+'|'+time
      RestClient.post('http://localhost:5140', [{:headers => {:host => 'web'}, :body => var}].to_json)
	    render :text => 'Data was sent to the Hadoop cluster.'
      @existingRecord.delete
      # end Send

    else
      @transaction = Transaction.new(transaction_params)
      @transaction.location = params[:location]
      @transaction.license_no = params[:license_no]
      @transaction.time = params[:time]
      if @transaction.save
        render :text => 'Data was buffered.'
      else
        render :status => :unprocessable_entity
      end
    end
  end

  def ensure_json_format
    if request.content_type != 'application/json'
      render :text => 'Wrong FORMAT!! Only JSON is accepted', :status => 406
    end
  end


  def generateOD
    $sumOfRoute.clear
    $arrayOfEndPoint.clear

    $transport.open

    temp1 = params[:rangeFrom].split('/')
    temp2 = params[:rangeTo].split('/')

    dateFrom = temp1[2].to_s+'-'+temp1[0].to_s+'-'+temp1[1].to_s
    dateTo = temp2[2].to_s+'-'+temp2[0].to_s+'-'+temp2[1].to_s

    # Return all the route in the request range from Hbase
    getRange = $hbaseClient.get("hbase_hive", ["*"],
                                "SingleColumnValueFilter('cf', 'time', "'>='", 'binary:#{dateFrom}') AND "+
                                    "SingleColumnValueFilter('cf', 'time', "'<='", 'binary:#{dateTo}')", {})

    $sumOfRoute = doSumHash(getRange) # Initiate Hash table to print in the dynamic OD table
    $arrayOfEndPoint = doArrayEndPoint(getRange) # Initiate number of end-points in the dynamic OD table

    respond_to do |format|
      format.html {redirect_to @transaction}
      format.js #render transaction/generateOD.js.erb
    end

    $transport.close
  end

  # Do Group by and Count for each entrypoint from Hbase
  def doSumHash(range)
    sumValue = Hash.new

    for i in 0..range.size-1
      if sumValue[range[i][1]].nil?
        sumValue[range[i][1]] = range[i][0].to_i
      else
        sumValue[range[i][1]] = sumValue[range[i][1]].to_i + range[i][0].to_i
      end
    end

    return sumValue
    sumValue.clear
  end

  # Generate the header of the OD table
  def doArrayEndPoint(range)
    arrayEndPoint = Array.new

    for i in 0..range.size-1
      var1 = range[i][1].split('-')[0]
      var2 = range[i][1].split('-')[1]

      if arrayEndPoint.index(var1).nil?
        arrayEndPoint << var1
      end

      if arrayEndPoint.index(var2).nil?
        arrayEndPoint << var2
      end
    end

    return arrayEndPoint
    arrayEndPoint.clear
  end

  # Generate the OD CSV file
  def getCSV
    tarray = Array.new

    csv_data = CSV.generate do |csv|
      tarray << 'OD Matrix'
      for i in 0..$arrayOfEndPoint.size-1
        tarray << $arrayOfEndPoint[i]
      end

      csv << tarray
      tarray.clear

      for i in 0..$arrayOfEndPoint.size-1
        tarray << $arrayOfEndPoint[i]
        for j in 0..$arrayOfEndPoint.size-1
          tarray << $sumOfRoute[$arrayOfEndPoint[i]+"-"+$arrayOfEndPoint[j]]
        end
        csv << tarray
        tarray.clear
      end
    end

    send_data csv_data, :type => 'text/csv; charset=iso-8859-1; header=present',
              :disposition => 'attachment; filename=OD_matrix.csv'
  end


  # GET /transactions
  # GET /transactions.json
  def index
    host = '192.168.1.11'
    port = 9090

    socket = Thrift::Socket.new(host, port)
    $transport = Thrift::BufferedTransport.new(socket)
    $transport.open
    protocol = Thrift::BinaryProtocol.new($transport)

    $hbaseClient = HBase::Client.new(protocol)
    $transport.close
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end
  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:location, :time, :license_no)
    end
end

tfMonitoring/app/helpers/application_helper.rb
module ApplicationHelper
end

tfMonitoring/app/helpers/transactions_helper.rb
module TransactionsHelper
end

tfMonitoring/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TfMonitoring</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!--<script src="https://code.jquery.com/jquery-2.2.3.min.js" ></script>-->

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Simple Sidebar - Start Bootstrap Template</title>

  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/simple-sidebar.css" rel="stylesheet">

  <script type="text/javascript">
    $(document).ready(function(){
      $('.datepicker').datepicker();
    });
  </script>

  <script>
    function myFunction() {
      document.getElementById("genOD").innerHTML = "Hello World";
    }
  </script>

  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>


  <script type="text/javascript">
    function getCSV(){
      $.get('/transaction/generateOD/getCSV');
    }
  </script>


</head>
<body>

<%= yield %>

</body>
</html>

tfMonitoring/app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :license_no %><br>
    <%= f.text_field :license_no %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tfMonitoring/app/views/transactions/_odTable.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th>OD Matrix</th>
    <% for i in 0..@a.size-1 %>
        <th><%= @a[i] %></th>
    <% end %>
  </tr>
  </thead>
  <tbody>
    <% for i in 0..@a.size-1 %>
      <tr>
        <th scope="row"><%= @a[i] %></th>
        <% for j in 0..@a.size-1 %>
            <td><%= @hash[@a[i]+"-"+@a[j]] %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

tfMonitoring/app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

tfMonitoring/app/views/transactions/generateOD.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th>OD Matrix</th>
    <% for i in 0..@a.size-1 %>
        <th><%= @a[i] %></th>
    <% end %>
  </tr>
  </thead>
  <tbody>
    <% for i in 0..@a.size-1 %>
      <tr>
        <th scope="row"><%= @a[i] %></th>
        <% for j in 0..@a.size-1 %>
            <td><%= @hash[@a[i]+"-"+@a[j]] %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

tfMonitoring/app/views/transactions/generateOD.js.erb
$('#ODMatrixPanel').html(
    '<table class="table table-bordered">' +
    '<thead>' +
    '<tr>' +
      '<th class="info">OD Matrix</th>'+
        '<% for i in 0..$arrayOfEndPoint.size-1 %>' +
      '<th class="info">' +
        '<%= $arrayOfEndPoint[i] %>' +
      '</th>' +
        '<% end %>' +
    '</tr> ' +
    '</thead>' +

    '<tbody>' +
      '<% for i in 0..$arrayOfEndPoint.size-1 %>' +
    '<tr>' +
      '<th scope="row" class="info">' +
        '<%= $arrayOfEndPoint[i] %>' +
      '</th>' +
      '<% for j in 0..$arrayOfEndPoint.size-1 %>' +
      '<td>' +
        '<%= $sumOfRoute[$arrayOfEndPoint[i]+"-"+$arrayOfEndPoint[j]] %>' +
      '</td>' +
          '<% end %>' +
    '</tr>' +
        '<% end %>' +
    '</tbody>' +
    '</table>' +
    '<p> Download: ' +
        '<%= link_to 'CSV', csv_event_path %>' +
    '</p>'
  );

tfMonitoring/app/views/transactions/index.html.erb
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        OD Matrix
                    </a>
                </li>
              <%= form_tag transaction_generateOD_path(:format => 'js'), remote: true, method: :get do -%>
                <li>
                  <%= text_field_tag :rangeFrom, 'Range from (click here)', class: 'datepicker'  %>
                </li>
                <li>
                    <p/>
                </li>
                <li>
                  <%= text_field_tag :rangeTo, 'Range to (click here)', class: 'datepicker'  %>
                </li>
                <li>
                    <p/>
                </li>
                <li>
                  <%= button_tag 'Submit', class: 'btn btn-mini btn-primary' %>
                </li>
              <% end %>
              <!--
                <li>
                    <a href="#">Contact</a>
                </li>
                -->
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class=".table-responsive" id="ODMatrixPanel">
                        <h1>Traffic monitoring service</h1>
                    </div>
                 <!-- <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle</a>-->
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

tfMonitoring/app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

tfMonitoring/app/views/transactions/show.html.erb
<%= @getRange %>